# Generated by Django 5.2.6 on 2025-09-28 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_tutor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationstate',
            options={'verbose_name': 'Estado de Conversación', 'verbose_name_plural': 'Estados de Conversación'},
        ),
        migrations.AlterField(
            model_name='conversationstate',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del estado.'),
        ),
        migrations.AlterField(
            model_name='conversationstate',
            name='state_json',
            field=models.JSONField(help_text='Almacena el estado del grafo de LangChain en formato JSON.'),
        ),
        migrations.AlterField(
            model_name='conversationstate',
            name='user',
            field=models.OneToOneField(help_text='Usuario al que pertenece este estado de conversación.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
